### ISSUE TITLE
VMD package broken in NUR

### ISSUE THREAD

**Issue by Panadestein** [Nix-QChem/NixOS-QChem#252]
Hello,

thanks for this very valuable compilation of quantum chemistry software. I have tried to use VMD with NUR in a quite recent version of the unstable channel, but there seems to be a problem with the graphics driver:

```console
(λ . loren) NIXPKGS_ALLOW_UNFREE=1 nix-shell -p nur.repos.qchem.vmd
error: 'libGL_driver' has been renamed to/replaced by 'mesa.drivers'
(use '--show-trace' to show detailed location information)
```

The strange thing is that in the derivation's `buildInputs` there is already `mesa.drivers`. How can this issue be solved? Thanks in advance.

Metadata:

```console
 (λ . loren) nix-shell -p nix-info --run "nix-info -m"
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.11, NixOS, 23.05 (Stoat), 23.05.20230213.545c7a3`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.13.2`
 - channels(loren): `""`
 - channels(root): `"nixos, nixos-unstable, unstable"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixos`
```

**Comment by markuskowa** [comment]
It looks like that he internal pinning of nixpkgs is not working properly for the NUR export. I will into it.

**Comment by markuskowa** [comment]
It appears the git commit in NUR has not been updated since late 2021. That means, that the version of NixOS-QChem that you see at the moment is more than a year old. I am not sure why NUR's update mechanism fails, since I can pass all tests that NUR recommends locally. 
One major problem may be that NUR says "DO NOT import packages for example with `import <nixpkgs> {};`". However, for us it is crucial to pin nixpkgs to a specific version as this is the only way to guarantee that both are compatible (we test everything on a local Hydra to before we pull up the nixpkgs commit).
I have no good idea how to fix this at the moment. The short term solution might be to remove the packages from NUR (and only export the overlay via NUR).

@Panadestein For now you might be better off using the overlay directly. You can also use it via flakes. However, for the flakes mechanism, you need to create an overlay flake to enable some unfree packages such as VMD.

**Comment by Panadestein** [comment]
@markuskowa thanks a lot for the explanation. I have already tried the flake `nix shell github:Nix-QChem/NixOS-QChem#PACKAGE`, and it is in fact my favorite solution. I saw in the `flake.nix` that VMD was set to null, now I think I know how to fix it.

**Comment by Panadestein** [comment]
@sheepforce thanks a lot! Your flake is really helpful. I am going to close the issue as it seems to be related to NUR and not NixOS-QChem, plus the flakes are a great solution anyway.
