### ISSUE TITLE
psi4: broken on nixpkgs-unstable lastest

### ISSUE THREAD

**Issue by markuskowa** [Nix-QChem/NixOS-QChem#303]
```
-- Suitable Libint2 could not be located, Building Libint2 from generator source instead.
CMake Warning at external/upstream/libint2/CMakeLists.txt:115 (message):
  Libint2 generator source build requires Ninja (not Makefile) builder
  and Boost, Eigen, and GMPXX dependencies.  The build will be very long for
  non-trivial AM, and parallelism won't help for the generation phase.  Edit
  external/upstream/libint2/CMakeLists.txt for AM, derivative, and integral
  classes settings.
```

**Comment by sheepforce** [comment]
This is actually noise I think and intended behaviour (I am explicitly forcing it to build the generator source). The actual problem seems to be Cmake trying to find CheMPS2 and getting `1.14.1-2` as a package name instead of a version or something like this. I am looking into it :+1:

**Comment by sheepforce** [comment]
The problem is in the CMake expression of either HDF5 or CheMPS2 somehow. In `share/cmake/CheMPS2/CheMPS2Version.cmake` there is `1.14.1-2` written as the minimum HDF5 version. This version string is not a valid cmake identifier for versions (it does not accept dashes, only dots). So the issue is just the hd5 1.14.1 -> 1.14.1-2 update upstream and that this version string breaks CMake.
