### ISSUE TITLE
Fix fallout from last nixpkgs staging merge

### ISSUE THREAD

**Issue by markuskowa** [Nix-QChem/NixOS-QChem#513]
The staging merge a few weeks a ago broke a few things.

- [ ] gau2grid (`No module named 'distutils'`)
- [ ] ambertools (`Checking for Python package distutils.sysconfig -- not found`)
- [ ] dftbplus (`No module named 'dptools'`)
- [ ] optking (`AttributeError: module 'configparser' has no attribute 'SafeConfigParser'. Did you mean: 'RawConfigParser'?`)
- [ ] pylibefp(`ModuleNotFoundError: No module named 'distutils'`)
- [ ] vmd-python
- [ ] xtb-python
- [ ] psi4 (`Could NOT find Python (missing: Python_NumPy_INCLUDE_DIRS NumPy) (found
  suitable version "3.11.9", minimum required is "3.8")`)
- [x] gamess-us

CC @sheepforce

**Comment by sheepforce** [comment]
I'm on vacation now for three weeks and can have a look on some of them when I'm back. However, most of them are python 3.12 problems and upstream will hopefully patch the soonish. Others such as xtb-python are simply dead and I think we should just mark it broken, while Ambertools will likely only be fixed with the next release next year. Maybe it is worth here to mark them explicitly only compatible with Python 3.11 instead of pouring endless work in fixes, that will come sooner or later anyways? :)

**Comment by markuskowa** [comment]
Ok, then the simplest solution is to keep python-3.11 around for a while and retire dead packages in the future.

**Comment by markuskowa** [comment]
The biggest issue here is gau2grid which is required by psi4. For the rest the backward compatibility scheme seems to be fine.

**Comment by berquist** [comment]
I am going to try and fix/modernize gau2grid upstream.

**Comment by sheepforce** [comment]
> I am going to try and fix/modernize gau2grid upstream.

I've made a simple workaround here:
https://github.com/Nix-QChem/NixOS-QChem/pull/521/commits/10b91d0c748481da492a14f1fdad35f24a69da79

Maybe it is also working for upstream. :)
